version: "3.7"

services:
    web:
        image: nginx:alpine
        working_dir: /src
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.my-bullion.rule=Host(`my-bullion.local.designbysweet.com`)"
            - "traefik.http.routers.my-bullion.tls=true"
        volumes:
            - ./etc/nginx/:/etc/nginx/conf.d/:delegated,ro
            - ./src:/src:delegated
        networks:
            - internal
            - traefik
    app:
        build:
            context: .
            dockerfile: ./etc/docker/app.dockerfile
        user: www-data
        working_dir: /src
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/00_mvc.ini:delegated,ro
            - ./src:/src:delegated
        networks:
            - internal
            - local-mysql
networks:
    internal:
    traefik:
        external: true
    local-mysql:
        external: true
